var config = [
  /****************************************** 		level 1 ----------- animals 		******************************************/
  {
    level: "1",
    theme: "greetings",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  {
    level: "1",
    theme: "greetings",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 3,
  },
  {
    level: "1",
    theme: "greetings",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "1",
    theme: "greetings",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  {
    level: "1",
    theme: "greetings",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 3,
  },
  {
    level: "1",
    theme: "greetings",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "1",
    theme: "greetings",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  /****************************************** 		level 2 ----------- animals 		******************************************/
  {
    level: "2",
    theme: "greetings",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  {
    level: "2",
    theme: "greetings",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 3,
  },
  {
    level: "2",
    theme: "greetings",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "2",
    theme: "greetings",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  {
    level: "2",
    theme: "greetings",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 3,
  },
  {
    level: "2",
    theme: "greetings",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "2",
    theme: "greetings",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  /****************************************** 		level 3 ----------- animals 		******************************************/
  {
    level: "3",
    theme: "greetings",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  {
    level: "3",
    theme: "greetings",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 3,
  },
  {
    level: "3",
    theme: "greetings",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "3",
    theme: "greetings",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  {
    level: "3",
    theme: "greetings",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 3,
  },
  {
    level: "3",
    theme: "greetings",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "3",
    theme: "greetings",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  /****************************************** 		level 4 ----------- animals 		******************************************/
  {
    level: "4",
    theme: "greetings",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  {
    level: "4",
    theme: "greetings",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 3,
  },
  {
    level: "4",
    theme: "greetings",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "4",
    theme: "greetings",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  {
    level: "4",
    theme: "greetings",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 3,
  },
  {
    level: "4",
    theme: "greetings",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "4",
    theme: "greetings",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  /****************************************** 		level 5 ----------- animals 		******************************************/
  {
    level: "5",
    theme: "greetings",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  {
    level: "5",
    theme: "greetings",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 3,
  },
  {
    level: "5",
    theme: "greetings",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "5",
    theme: "greetings",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  {
    level: "5",
    theme: "greetings",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 3,
  },
  {
    level: "5",
    theme: "greetings",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "5",
    theme: "greetings",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  /****************************************** 		level 1 ----------- body 		******************************************/
  {
    level: "1",
    theme: "body",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  {
    level: "1",
    theme: "body",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 3,
  },
  {
    level: "1",
    theme: "body",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "1",
    theme: "body",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  {
    level: "1",
    theme: "body",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 3,
  },
  {
    level: "1",
    theme: "body",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "1",
    theme: "body",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  /****************************************** 		level 2 ----------- body 		******************************************/
  {
    level: "2",
    theme: "body",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  {
    level: "2",
    theme: "body",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 3,
  },
  {
    level: "2",
    theme: "body",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "2",
    theme: "body",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  {
    level: "2",
    theme: "body",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 3,
  },
  {
    level: "2",
    theme: "body",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "2",
    theme: "body",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  /****************************************** 		level 3 ----------- body 		******************************************/
  {
    level: "3",
    theme: "body",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  {
    level: "3",
    theme: "body",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 3,
  },
  {
    level: "3",
    theme: "body",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "3",
    theme: "body",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  {
    level: "3",
    theme: "body",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 3,
  },
  {
    level: "3",
    theme: "body",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "3",
    theme: "body",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  /****************************************** 		level 4 ----------- body 		******************************************/
  {
    level: "4",
    theme: "body",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  {
    level: "4",
    theme: "body",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 3,
  },
  {
    level: "4",
    theme: "body",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "4",
    theme: "body",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  {
    level: "4",
    theme: "body",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 3,
  },
  {
    level: "4",
    theme: "body",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "4",
    theme: "body",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  /****************************************** 		level 5 ----------- body 		******************************************/
  {
    level: "5",
    theme: "body",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  {
    level: "5",
    theme: "body",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 3,
  },
  {
    level: "5",
    theme: "body",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "5",
    theme: "body",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  {
    level: "5",
    theme: "body",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 3,
  },
  {
    level: "5",
    theme: "body",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "5",
    theme: "body",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  /****************************************** 		level 1 ----------- Family 		******************************************/
  {
    level: "1",
    theme: "family",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 1,
  },
  {
    level: "1",
    theme: "family",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 1,
  },
  {
    level: "1",
    theme: "family",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "1",
    theme: "family",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  {
    level: "1",
    theme: "family",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 3,
  },
  {
    level: "1",
    theme: "family",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "1",
    theme: "family",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  /****************************************** 		level 2 ----------- family 		******************************************/
  {
    level: "2",
    theme: "family",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 1,
  },
  {
    level: "2",
    theme: "family",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 1,
  },
  {
    level: "2",
    theme: "family",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "2",
    theme: "family",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  {
    level: "2",
    theme: "family",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 3,
  },
  {
    level: "2",
    theme: "family",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "2",
    theme: "family",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  /****************************************** 		level 3 ----------- family 		******************************************/
  {
    level: "3",
    theme: "family",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 1,
  },
  {
    level: "3",
    theme: "family",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 1,
  },
  {
    level: "3",
    theme: "family",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "3",
    theme: "family",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  {
    level: "3",
    theme: "family",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 3,
  },
  {
    level: "3",
    theme: "family",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "3",
    theme: "family",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  /****************************************** 		level 4 ----------- family 		******************************************/
  {
    level: "4",
    theme: "family",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 1,
  },
  {
    level: "4",
    theme: "family",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 1,
  },
  {
    level: "4",
    theme: "family",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "4",
    theme: "family",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  {
    level: "4",
    theme: "family",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 3,
  },
  {
    level: "4",
    theme: "family",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "4",
    theme: "family",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  /****************************************** 		level 5 ----------- family 		******************************************/
  {
    level: "5",
    theme: "family",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 1,
  },
  {
    level: "5",
    theme: "family",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 1,
  },
  {
    level: "5",
    theme: "family",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "5",
    theme: "family",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  {
    level: "5",
    theme: "family",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 3,
  },
  {
    level: "5",
    theme: "family",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "5",
    theme: "family",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  /****************************************** 		level 1 ----------- House 		******************************************/
  {
    level: "1",
    theme: "house",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 1,
  },
  {
    level: "1",
    theme: "house",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 1,
  },
  {
    level: "1",
    theme: "house",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "1",
    theme: "house",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  {
    level: "1",
    theme: "house",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 3,
  },
  {
    level: "1",
    theme: "house",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "1",
    theme: "house",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  /****************************************** 		level 2 ----------- safety 		******************************************/
  {
    level: "2",
    theme: "house",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 1,
  },
  {
    level: "2",
    theme: "house",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 1,
  },
  {
    level: "2",
    theme: "house",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "2",
    theme: "house",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  {
    level: "2",
    theme: "house",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 3,
  },
  {
    level: "2",
    theme: "house",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "2",
    theme: "house",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  /****************************************** 		level 3 ----------- safety 		******************************************/
  {
    level: "3",
    theme: "house",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 1,
  },
  {
    level: "3",
    theme: "house",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 1,
  },
  {
    level: "3",
    theme: "house",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "3",
    theme: "house",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  {
    level: "3",
    theme: "house",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 3,
  },
  {
    level: "3",
    theme: "house",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "3",
    theme: "house",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  /****************************************** 		level 4 ----------- safety 		******************************************/
  {
    level: "4",
    theme: "house",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 1,
  },
  {
    level: "4",
    theme: "house",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 1,
  },
  {
    level: "4",
    theme: "house",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "4",
    theme: "house",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  {
    level: "4",
    theme: "house",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 3,
  },
  {
    level: "4",
    theme: "house",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "4",
    theme: "house",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  /****************************************** 		level 5 ----------- family 		******************************************/
  {
    level: "5",
    theme: "house",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 1,
  },
  {
    level: "5",
    theme: "house",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 1,
  },
  {
    level: "5",
    theme: "house",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "5",
    theme: "house",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  {
    level: "5",
    theme: "house",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 3,
  },
  {
    level: "5",
    theme: "house",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "5",
    theme: "house",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  /****************************************** 		level 1 ----------- school 		******************************************/
  {
    level: "1",
    theme: "school",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 1,
  },
  {
    level: "1",
    theme: "school",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 1,
  },
  {
    level: "1",
    theme: "school",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "1",
    theme: "school",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  {
    level: "1",
    theme: "school",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 3,
  },
  {
    level: "1",
    theme: "school",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "1",
    theme: "school",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  /****************************************** 		level 2 ----------- food 		******************************************/
  {
    level: "2",
    theme: "school",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 1,
  },
  {
    level: "2",
    theme: "school",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 1,
  },
  {
    level: "2",
    theme: "school",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "2",
    theme: "school",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  {
    level: "2",
    theme: "school",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 3,
  },
  {
    level: "2",
    theme: "school",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "2",
    theme: "school",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  /****************************************** 		level 3 ----------- food 		******************************************/
  {
    level: "3",
    theme: "school",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 1,
  },
  {
    level: "3",
    theme: "school",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 1,
  },
  {
    level: "3",
    theme: "school",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "3",
    theme: "school",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  {
    level: "3",
    theme: "school",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 3,
  },
  {
    level: "3",
    theme: "school",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "3",
    theme: "school",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  /****************************************** 		level 4 ----------- food 		******************************************/
  {
    level: "4",
    theme: "school",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 1,
  },
  {
    level: "4",
    theme: "school",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 1,
  },
  {
    level: "4",
    theme: "school",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "4",
    theme: "school",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  {
    level: "4",
    theme: "school",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 3,
  },
  {
    level: "4",
    theme: "school",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "4",
    theme: "school",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  /****************************************** 		level 5 ----------- food 		******************************************/
  {
    level: "5",
    theme: "school",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 1,
  },
  {
    level: "5",
    theme: "school",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 1,
  },
  {
    level: "5",
    theme: "school",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "5",
    theme: "school",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
  {
    level: "5",
    theme: "school",
    question: "How do you reply to Good Morning in Arabic?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 3,
  },
  {
    level: "5",
    theme: "school",
    question: "What is the arabic translation of - 'Good Evening ?",
    answers: ["صباح الخير", "مع السلامة", "صباح النور", "مساء الخير"],
    correct: 2,
  },
  {
    level: "5",
    theme: "school",
    question: "What is the arabic translation of - 'Good Morning ?",
    answers: ["مع السلامة", "صباح النور", "صباح الخير", "لو سمحت"],
    correct: 2,
  },
];
